#NAME:Qinglin Zhang
#EMAIL: qqinglin0327@gmail.com
#ID: 205356739
#

default:
	gcc -Wall -Wextra -lz -o lab1b-client lab1b-client.c
	gcc -Wall -Wextra -lz -o lab1b-server lab1b-server.c
clean:
	rm -f lab1b-205356739.tar.gz lab1b-client lab1b-server
dist: 
	tar -cvzf lab1b-205356739.tar.gz lab1b-client.c lab1b-server.c README Makefile
