# NAME: Qinglin ZHang
# EMAIL: qqinglin0327@gmail.com
# ID: 205356739

default:
	gcc -g -Wall -Wextra lab1a.c -o lab1a

clean:
	rm -f lab1a lab1a-205356739.tar.gz

dist:
	tar -cvzf lab1a-205356739.tar.gz lab1a.c README Makefile
